services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  orderservice:
    build: ./src/OrderService
    depends_on:
      - kafka
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      KAFKA_BROKERS: kafka:9092

  paymentservice:
    build: ./src/PaymentService
    depends_on:
      - kafka
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      KAFKA_BROKERS: kafka:9092

  shippingservice:
    build: ./src/ShippingService
    depends_on:
      - kafka
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      KAFKA_BROKERS: kafka:9092

  notificationservice:
    build: ./src/NotificationService
    depends_on:
      - kafka
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      KAFKA_BROKERS: kafka:9092